### ISSUE TITLE
error on selectFeatures 

### ISSUE THREAD

**Issue by rersister** [BaderLab/CellAnnotationTutorial#2]
I am learning your method to annotate single cell. What an amazing work. But I come across  this same question (https://github.com/hemberg-lab/scmap/issues/31#issue-966047805 )when I choose 'celldex::NovershternHematopoieticData()' as ref. Could you help me? What should I do? I need this dataset as my ref to annotate  my  bone marrow sample.Thanks.

**Comment by 14zac2** [comment]
Hi @rersister - interesting problem! I tried loading the dataset and couldn't find any obvious clues as to what was throwing the error (which I also experienced). It seems like there may be NAs somewhere in the `celldex::NovershternHematopoieticData()` which is causing the linear model not to work. Hopefully the makers of scmap responds to the thread you referenced, as the only other thing I could do is try to narrow down the differences between both datasets. When looking at the help page for the function (`?selectFeatures`), it mentions some reasons as to why it might not work. This is all I can offer for now, but if I find anything else, I'll let you know!
